 
CREATE TABLE ESTADO
	(
	ID_ESTADO INT IDENTITY(1,1),
	ESTADO VARCHAR(200),
	SIGLA VARCHAR(10)	
	CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO)
	)

	-- TABELA CIDADE
CREATE TABLE CIDADE
	(
	ID_CIDADE INT IDENTITY(1,1),
	CIDADE VARCHAR(200),
	ID_ESTADO INT
	CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE),
	CONSTRAINT FK_ESTADO_CIDADE FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
	)
	-- TABELA ENDERECO
CREATE TABLE ENDERECO
	(
	ID_ENDERECO INT IDENTITY(1,1),
	LOGRADOURO VARCHAR(300),
	NUMERO INT,
	CEP VARCHAR(50),
	ID_CIDADE INT
	CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_ENDERECO),
	CONSTRAINT FK_CIDADE_ENDERECO FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
	)
	--TABELA CLIENTE  
CREATE TABLE CLIENTE
	(
	ID_CLIENTE INT IDENTITY(1,1),
	CNPJ_CPF VARCHAR(500),
	NOME VARCHAR(200),
	NOME_FANTASIA VARCHAR(200),
	DATA_CADASTRO DATE,
	ID_ENDERECO INT,
	DATA_NASCIMENTO DATE
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
	)
	 
	   	  --TABELA PEDIDO  
CREATE TABLE PEDIDO
	(
	ID_PEDIDO INT IDENTITY(1,1),
	CONTRATO INT NOT NULL,
	VALOR DECIMAL(18,2) NOT NULL,
	QUANTIDADE INT NOT NULL,
	DATA_PEDIDO DATE NOT NULL,
	ID_CLIENTE INT NOT NULL,
	VALOR_TOTAL DECIMAL(18,2) NOT NULL,
	QUANTIDADE_TOTAL INT NOT NULL
	CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
	)
	--TABELA MAQUINA
CREATE TABLE MAQUINA
	(
	ID_MAQUINA INT IDENTITY(1,1),
	CODIGO INT,
	NOME VARCHAR(200),
	DESCRICAO VARCHAR(200)
	CONSTRAINT PK_MAQUINA PRIMARY KEY (ID_MAQUINA)
	)
	--TABELA ITEM PEDIDO
CREATE TABLE ITEM_PEDIDO
	(
	ID_ITEM_PEDIDO INT IDENTITY(1,1),
	ID_MAQUINA INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR_TOTAL DECIMAL(18,2) NOT NULL
	CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY (ID_ITEM_PEDIDO),
	CONSTRAINT FK_PEDIDO_ITEMPEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
	CONSTRAINT FK_MAQUINA_ITEMPEDIDO FOREIGN KEY (ID_MAQUINA) REFERENCES MAQUINA(ID_MAQUINA)
	)

	--3 ALTER TABLE

--Crie uma nova coluna chamada “COR” VARCHAR (50).
ALTER TABLE MAQUINA
ADD COR VARCHAR(50)


--Crie uma restrição na coluna CNPJ_CPF para que esse valor seja ÚNICO.
ALTER TABLE CLIENTE
ADD CONSTRAINT UNIQUE_CPF_CNPJ UNIQUE (CNPJ_CPF)

--Remova a coluna NOME_FANTASIA.
ALTER TABLE CLIENTE
DROP COLUMN NOME_FANTASIA

--Crie uma nova coluna chamada “TELEFONE” VARCHAR (100).
ALTER TABLE CLIENTE
ADD TELEFONE VARCHAR(100)